<?php

namespace App\Enums;

enum CountryEnum: string
{
    use EnumHelper;

    case AFGHANISTAN = 'Afghanistan';
    case ALBANIA = 'Albania';
    case ALGERIA = 'Algeria';
    case ANDORRA = 'Andorra';
    case ANGOLA = 'Angola';
    case ANTIGUA_AND_BARBUDA = 'Antigua and Barbuda';
    case ARGENTINA = 'Argentina';
    case ARMENIA = 'Armenia';
    case AUSTRALIA = 'Australia';
    case AUSTRIA = 'Austria';
    case AZERBAIJAN = 'Azerbaijan';
    case BAHAMAS = 'Bahamas';
    case BAHRAIN = 'Bahrain';
    case BANGLADESH = 'Bangladesh';
    case BARBADOS = 'Barbados';
    case BELARUS = 'Belarus';
    case BELGIUM = 'Belgium';
    case BELIZE = 'Belize';
    case BENIN = 'Benin';
    case BHUTAN = 'Bhutan';
    case BOLIVIA = 'Bolivia';
    case BOSNIA_AND_HERZEGOVINA = 'Bosnia and Herzegovina';
    case BOTSWANA = 'Botswana';
    case BRAZIL = 'Brazil';
    case BRUNEI = 'Brunei';
    case BULGARIA = 'Bulgaria';
    case BURKINA_FASO = 'Burkina Faso';
    case BURUNDI = 'Burundi';
    case CABO_VERDE = 'Cabo Verde';
    case CAMBODIA = 'Cambodia';
    case CAMEROON = 'Cameroon';
    case CANADA = 'Canada';
    case CENTRAL_AFRICAN_REPUBLIC = 'Central African Republic';
    case CHAD = 'Chad';
    case CHILE = 'Chile';
    case CHINA = 'China';
    case COLOMBIA = 'Colombia';
    case COMOROS = 'Comoros';
    case CONGO = 'Congo';
    case COSTA_RICA = 'Costa Rica';
    case CROATIA = 'Croatia';
    case CUBA = 'Cuba';
    case CYPRUS = 'Cyprus';
    case CZECH_REPUBLIC = 'Czech Republic';
    case DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'Democratic Republic of the Congo';
    case DENMARK = 'Denmark';
    case DJIBOUTI = 'Djibouti';
    case DOMINICA = 'Dominica';
    case DOMINICAN_REPUBLIC = 'Dominican Republic';
    case EAST_TIMOR = 'East Timor';
    case ECUADOR = 'Ecuador';
    case EGYPT = 'Egypt';
    case EL_SALVADOR = 'El Salvador';
    case EQUATORIAL_GUINEA = 'Equatorial Guinea';
    case ERITREA = 'Eritrea';
    case ESTONIA = 'Estonia';
    case ETHIOPIA = 'Ethiopia';
    case FIJI = 'Fiji';
    case FINLAND = 'Finland';
    case FRANCE = 'France';
    case GABON = 'Gabon';
    case GAMBIA = 'Gambia';
    case GEORGIA = 'Georgia';
    case GERMANY = 'Germany';
    case GHANA = 'Ghana';
    case GREECE = 'Greece';
    case GRENADA = 'Grenada';
    case GUATEMALA = 'Guatemala';
    case GUINEA = 'Guinea';
    case GUINEA_BISSAU = 'Guinea-Bissau';
    case GUYANA = 'Guyana';
    case HAITI = 'Haiti';
    case HONDURAS = 'Honduras';
    case HUNGARY = 'Hungary';
    case ICELAND = 'Iceland';
    case INDIA = 'India';
    case INDONESIA = 'Indonesia';
    case IRAN = 'Iran';
    case IRAQ = 'Iraq';
    case IRELAND = 'Ireland';
    case ISRAEL = 'Israel';
    case ITALY = 'Italy';
    case IVORY_COAST = 'Ivory Coast';
    case JAMAICA = 'Jamaica';
    case JAPAN = 'Japan';
    case JORDAN = 'Jordan';
    case KAZAKHSTAN = 'Kazakhstan';
    case KENYA = 'Kenya';
    case KIRIBATI = 'Kiribati';
    case KOSOVO = 'Kosovo';
    case KUWAIT = 'Kuwait';
    case KYRGYZSTAN = 'Kyrgyzstan';
    case LAOS = 'Laos';
    case LATVIA = 'Latvia';
    case LEBANON = 'Lebanon';
    case LESOTHO = 'Lesotho';
    case LIBERIA = 'Liberia';
    case LIBYA = 'Libya';
    case LIECHTENSTEIN = 'Liechtenstein';
    case LITHUANIA = 'Lithuania';
    case LUXEMBOURG = 'Luxembourg';
    case MACAO = 'Macao';
    case MACEDONIA = 'Macedonia';
    case MADAGASCAR = 'Madagascar';
    case MALAWI = 'Malawi';
    case MALAYSIA = 'Malaysia';
    case MALDIVES = 'Maldives';
    case MALI = 'Mali';
    case MALTA = 'Malta';
    case MARSHALL_ISLANDS = 'Marshall Islands';
    case MAURITANIA = 'Mauritania';
    case MAURITIUS = 'Mauritius';
    case MEXICO = 'Mexico';
    case MICRONESIA = 'Micronesia';
    case MOLDOVA = 'Moldova';
    case MONACO = 'Monaco';
    case MONGOLIA = 'Mongolia';
    case MONTENEGRO = 'Montenegro';
    case MOROCCO = 'Morocco';
    case MOZAMBIQUE = 'Mozambique';
    case MYANMAR = 'Myanmar';
    case NAMIBIA = 'Namibia';
    case NAURU = 'Nauru';
    case NEPAL = 'Nepal';
    case NETHERLANDS = 'Netherlands';
    case NEW_ZEALAND = 'New Zealand';
    case NICARAGUA = 'Nicaragua';
    case NIGER = 'Niger';
    case NIGERIA = 'Nigeria';
    case NORTH_KOREA = 'North Korea';
    case NORTH_MACEDONIA = 'North Macedonia';
    case NORWAY = 'Norway';
    case OMAN = 'Oman';
    case PAKISTAN = 'Pakistan';
    case PALAU = 'Palau';
    case PALESTINE = 'Palestine';
    case PANAMA = 'Panama';
    case PAPUA_NEW_GUINEA = 'Papua New Guinea';
    case PARAGUAY = 'Paraguay';
    case PERU = 'Peru';
    case PHILIPPINES = 'Philippines';
    case POLAND = 'Poland';
    case PORTUGAL = 'Portugal';
    case QATAR = 'Qatar';
    case ROMANIA = 'Romania';
    case RUSSIA = 'Russia';
    case RWANDA = 'Rwanda';
    case SAINT_KITTS_AND_NEVIS = 'Saint Kitts and Nevis';
    case SAINT_LUCIA = 'Saint Lucia';
    case SAINT_VINCENT_AND_THE_GRENADINES = 'Saint Vincent and the Grenadines';
    case SAMOA = 'Samoa';
    case SAN_MARINO = 'San Marino';
    case SAO_TOME_AND_PRINCIPE = 'Sao Tome and Principe';
    case SAUDI_ARABIA = 'Saudi Arabia';
    case SENEGAL = 'Senegal';
    case SERBIA = 'Serbia';
    case SEYCHELLES = 'Seychelles';
    case SIERRA_LEONE = 'Sierra Leone';
    case SINGAPORE = 'Singapore';
    case SLOVAKIA = 'Slovakia';
    case SLOVENIA = 'Slovenia';
    case SOLOMON_ISLANDS = 'Solomon Islands';
    case SOMALIA = 'Somalia';
    case SOUTH_AFRICA = 'South Africa';
    case SOUTH_KOREA = 'South Korea';
    case SOUTH_SUDAN = 'South Sudan';
    case SPAIN = 'Spain';
    case SRI_LANKA = 'Sri Lanka';
    case SUDAN = 'Sudan';
    case SURINAME = 'Suriname';
    case SWAZILAND = 'Swaziland';
    case SWEDEN = 'Sweden';
    case SWITZERLAND = 'Switzerland';
    case SYRIA = 'Syria';
    case TAIWAN = 'Taiwan';
    case TAJIKISTAN = 'Tajikistan';
    case TANZANIA = 'Tanzania';
    case THAILAND = 'Thailand';
    case TOGO = 'Togo';
    case TONGA = 'Tonga';
    case TRINIDAD_AND_TOBAGO = 'Trinidad and Tobago';
    case TUNISIA = 'Tunisia';
    case TURKEY = 'Turkey';
    case TURKMENISTAN = 'Turkmenistan';
    case TUVALU = 'Tuvalu';
    case UGANDA = 'Uganda';
    case UKRAINE = 'Ukraine';
    case UNITED_ARAB_EMIRATES = 'United Arab Emirates';
    case UNITED_KINGDOM = 'United Kingdom';
    case UNITED_STATES = 'United States';
    case URUGUAY = 'Uruguay';
    case UZBEKISTAN = 'Uzbekistan';
    case VANUATU = 'Vanuatu';
    case VATICAN_CITY = 'Vatican City';
    case VENEZUELA = 'Venezuela';
    case VIETNAM = 'Vietnam';
    case YEMEN = 'Yemen';
    case ZAMBIA = 'Zambia';
    case ZIMBABWE = 'Zimbabwe';

    public function label(): string
    {
        return match($this) {
            self::AFGHANISTAN => 'Afeganistão',
            self::ALBANIA => 'Albânia',
            self::ALGERIA => 'Argélia',
            self::ANDORRA => 'Andorra',
            self::ANGOLA => 'Angola',
            self::ANTIGUA_AND_BARBUDA => 'Antígua e Barbuda',
            self::ARGENTINA => 'Argentina',
            self::ARMENIA => 'Armênia',
            self::AUSTRALIA => 'Austrália',
            self::AUSTRIA => 'Áustria',
            self::AZERBAIJAN => 'Azerbaijão',
            self::BAHAMAS => 'Bahamas',
            self::BAHRAIN => 'Bahrein',
            self::BANGLADESH => 'Bangladesh',
            self::BARBADOS => 'Barbados',
            self::BELARUS => 'Belarus',
            self::BELGIUM => 'Bélgica',
            self::BELIZE => 'Belize',
            self::BENIN => 'Benin',
            self::BHUTAN => 'Butão',
            self::BOLIVIA => 'Bolívia',
            self::BOSNIA_AND_HERZEGOVINA => 'Bósnia e Herzegovina',
            self::BOTSWANA => 'Botsuana',
            self::BRAZIL => 'Brasil',
            self::BRUNEI => 'Brunei',
            self::BULGARIA => 'Bulgária',
            self::BURKINA_FASO => 'Burkina Faso',
            self::BURUNDI => 'Burundi',
            self::CABO_VERDE => 'Cabo Verde',
            self::CAMBODIA => 'Camboja',
            self::CAMEROON => 'Camarões',
            self::CANADA => 'Canadá',
            self::CENTRAL_AFRICAN_REPUBLIC => 'República Centro-Africana',
            self::CHAD => 'Chade',
            self::CHILE => 'Chile',
            self::CHINA => 'China',
            self::COLOMBIA => 'Colômbia',
            self::COMOROS => 'Comores',
            self::CONGO => 'Congo',
            self::COSTA_RICA => 'Costa Rica',
            self::CROATIA => 'Croácia',
            self::CUBA => 'Cuba',
            self::CYPRUS => 'Chipre',
            self::CZECH_REPUBLIC => 'República Tcheca',
            self::DEMOCRATIC_REPUBLIC_OF_THE_CONGO => 'República Democrática do Congo',
            self::DENMARK => 'Dinamarca',
            self::DJIBOUTI => 'Djibouti',
            self::DOMINICA => 'Dominica',
            self::DOMINICAN_REPUBLIC => 'República Dominicana',
            self::EAST_TIMOR => 'Timor-Leste',
            self::ECUADOR => 'Equador',
            self::EGYPT => 'Egito',
            self::EL_SALVADOR => 'El Salvador',
            self::EQUATORIAL_GUINEA => 'Guiné Equatorial',
            self::ERITREA => 'Eritreia',
            self::ESTONIA => 'Estônia',
            self::ETHIOPIA => 'Etiópia',
            self::FIJI => 'Fiji',
            self::FINLAND => 'Finlândia',
            self::FRANCE => 'França',
            self::GABON => 'Gabão',
            self::GAMBIA => 'Gâmbia',
            self::GEORGIA => 'Geórgia',
            self::GERMANY => 'Alemanha',
            self::GHANA => 'Gana',
            self::GREECE => 'Grécia',
            self::GRENADA => 'Granada',
            self::GUATEMALA => 'Guatemala',
            self::GUINEA => 'Guiné',
            self::GUINEA_BISSAU => 'Guiné-Bissau',
            self::GUYANA => 'Guiana',
            self::HAITI => 'Haiti',
            self::HONDURAS => 'Honduras',
            self::HUNGARY => 'Hungria',
            self::ICELAND => 'Islândia',
            self::INDIA => 'Índia',
            self::INDONESIA => 'Indonésia',
            self::IRAN => 'Irã',
            self::IRAQ => 'Iraque',
            self::IRELAND => 'Irlanda',
            self::ISRAEL => 'Israel',
            self::ITALY => 'Itália',
            self::IVORY_COAST => 'Costa do Marfim',
            self::JAMAICA => 'Jamaica',
            self::JAPAN => 'Japão',
            self::JORDAN => 'Jordânia',
            self::KAZAKHSTAN => 'Cazaquistão',
            self::KENYA => 'Quênia',
            self::KIRIBATI => 'Kiribati',
            self::KOSOVO => 'Kosovo',
            self::KUWAIT => 'Kuwait',
            self::KYRGYZSTAN => 'Quirguistão',
            self::LAOS => 'Laos',
            self::LATVIA => 'Letônia',
            self::LEBANON => 'Líbano',
            self::LESOTHO => 'Lesoto',
            self::LIBERIA => 'Libéria',
            self::LIBYA => 'Líbia',
            self::LIECHTENSTEIN => 'Liechtenstein',
            self::LITHUANIA => 'Lituânia',
            self::LUXEMBOURG => 'Luxemburgo',
            self::MACAO => 'Macau',
            self::MACEDONIA => 'Macedônia do Norte',
            self::MADAGASCAR => 'Madagascar',
            self::MALAWI => 'Malawi',
            self::MALAYSIA => 'Malásia',
            self::MALDIVES => 'Maldivas',
            self::MALI => 'Mali',
            self::MALTA => 'Malta',
            self::MARSHALL_ISLANDS => 'Ilhas Marshall',
            self::MAURITANIA => 'Mauritânia',
            self::MAURITIUS => 'Maurício',
            self::MEXICO => 'México',
            self::MICRONESIA => 'Micronésia',
            self::MOLDOVA => 'Moldávia',
            self::MONACO => 'Mônaco',
            self::MONGOLIA => 'Mongólia',
            self::MONTENEGRO => 'Montenegro',
            self::MOROCCO => 'Marrocos',
            self::MOZAMBIQUE => 'Moçambique',
            self::MYANMAR => 'Mianmar',
            self::NAMIBIA => 'Namíbia',
            self::NAURU => 'Nauru',
            self::NEPAL => 'Nepal',
            self::NETHERLANDS => 'Países Baixos',
            self::NEW_ZEALAND => 'Nova Zelândia',
            self::NICARAGUA => 'Nicarágua',
            self::NIGER => 'Níger',
            self::NIGERIA => 'Nigéria',
            self::NORTH_KOREA => 'Coreia do Norte',
            self::NORTH_MACEDONIA => 'Macedônia do Norte',
            self::NORWAY => 'Noruega',
            self::OMAN => 'Omã',
            self::PAKISTAN => 'Paquistão',
            self::PALAU => 'Palau',
            self::PALESTINE => 'Palestina',
            self::PANAMA => 'Panamá',
            self::PAPUA_NEW_GUINEA => 'Papua Nova Guiné',
            self::PARAGUAY => 'Paraguai',
            self::PERU => 'Peru',
            self::PHILIPPINES => 'Filipinas',
            self::POLAND => 'Polônia',
            self::PORTUGAL => 'Portugal',
            self::QATAR => 'Catar',
            self::ROMANIA => 'Romênia',
            self::RUSSIA => 'Rússia',
            self::RWANDA => 'Ruanda',
            self::SAINT_KITTS_AND_NEVIS => 'São Cristóvão e Nevis',
            self::SAINT_LUCIA => 'Santa Lúcia',
            self::SAINT_VINCENT_AND_THE_GRENADINES => 'São Vicente e Granadinas',
            self::SAMOA => 'Samoa',
            self::SAN_MARINO => 'San Marino',
            self::SAO_TOME_AND_PRINCIPE => 'São Tomé e Príncipe',
            self::SAUDI_ARABIA => 'Arábia Saudita',
            self::SENEGAL => 'Senegal',
            self::SERBIA => 'Sérvia',
            self::SEYCHELLES => 'Seicheles',
            self::SIERRA_LEONE => 'Serra Leoa',
            self::SINGAPORE => 'Singapura',
            self::SLOVAKIA => 'Eslováquia',
            self::SLOVENIA => 'Eslovênia',
            self::SOLOMON_ISLANDS => 'Ilhas Salomão',
            self::SOMALIA => 'Somália',
            self::SOUTH_AFRICA => 'África do Sul',
            self::SOUTH_KOREA => 'Coreia do Sul',
            self::SOUTH_SUDAN => 'Sudão do Sul',
            self::SPAIN => 'Espanha',
            self::SRI_LANKA => 'Sri Lanka',
            self::SUDAN => 'Sudão',
            self::SURINAME => 'Suriname',
            self::SWAZILAND => 'Eswatini',
            self::SWEDEN => 'Suécia',
            self::SWITZERLAND => 'Suíça',
            self::SYRIA => 'Síria',
            self::TAIWAN => 'Taiwan',
            self::TAJIKISTAN => 'Tajiquistão',
            self::TANZANIA => 'Tanzânia',
            self::THAILAND => 'Tailândia',
            self::TOGO => 'Togo',
            self::TONGA => 'Tonga',
            self::TRINIDAD_AND_TOBAGO => 'Trindade e Tobago',
            self::TUNISIA => 'Tunísia',
            self::TURKEY => 'Turquia',
            self::TURKMENISTAN => 'Turcomenistão',
            self::TUVALU => 'Tuvalu',
            self::UGANDA => 'Uganda',
            self::UKRAINE => 'Ucrânia',
            self::UNITED_ARAB_EMIRATES => 'Emirados Árabes Unidos',
            self::UNITED_KINGDOM => 'Reino Unido',
            self::UNITED_STATES => 'Estados Unidos',
            self::URUGUAY => 'Uruguai',
            self::UZBEKISTAN => 'Uzbequistão',
            self::VANUATU => 'Vanuatu',
            self::VATICAN_CITY => 'Cidade do Vaticano',
            self::VENEZUELA => 'Venezuela',
            self::VIETNAM => 'Vietnã',
            self::YEMEN => 'Iêmen',
            self::ZAMBIA => 'Zâmbia',
            self::ZIMBABWE => 'Zimbábue',
            default => null
        };
    }
    

}